### ISSUE TITLE
Don't use pip's internal API

### ISSUE THREAD

**Issue by di** [di/pytest-reqs#13]
Right now this library is abusing pip's internal API in a number of places.

In pip 10, most of these will need to get updated due to restructuring of the package internals.

Instead of making these updates, and having to feature-detect the version of pip, this library should switch to using pip properly (by shelling out and running pip directly) instead of depending on the internal API.

**Comment by maxnordlund** [comment]
Pip 10 broke this package, they finally moved the API into _internal. https://pip.pypa.io/en/stable/news/#deprecations-and-removals

On the flip side, 9.0.3 seems to work just fine.

**Comment by di** [comment]
Sorry this broke for you. I'm working on an alternative (https://github.com/di/pip-api) but it doesn't yet support all the features `pytest-reqs` needs yet. I'll likely have more time to work on that in the upcoming weeks, so stay tuned!

**Comment by maxnordlund** [comment]
OMG amazing, love to try it out. Please ping here and I'll happily provide some feedback.
