### ISSUE TITLE
pytest_reqs.py: 'Distribution' object has no attribute 'project_name'

### ISSUE THREAD

**Issue by KVGarg** [di/pytest-reqs#43]
The `Distribution` object has no attribute `project_name` else it has a attribute named `name`.
https://github.com/di/pip-api/blob/master/pip_api/_installed_distributions.py#L11

**Comment by KVGarg** [comment]
@di Running `pytest` on this project is working fine, but facing issues on other repositories. It is raising the error `'Distribution' object has no attribute 'project_name'`
Replacing the `project_name` by `name` is working perfectly which makes the build pass. Also, changing `installed_distributions.project_name` to just `name` is also working fine.

**Comment by di** [comment]
This has been fixed in 0.2.1, thanks! https://pypi.org/project/pytest-reqs/0.2.1/
